title: 伊索的故事 - 晚安．月亮
description: 伊索的故事 - 晚安．月亮
time: Mon, 02 Sep 2024 20:08:26 +0000
items:
  - title: 00. 伊索的故事
    size: 973158
    duration: 97
  - title: 01. 眾神的施恩
    size: 4722803
    duration: 500
  - title: 02. 淪為奴隸
    size: 3943986
    duration: 442
  - title: 03. 奴隸買賣
    size: 4336872
    duration: 461
  - title: 04. 主人克山特斯
    size: 3784947
    duration: 418
  - title: 05. 像主人的奴隸
    size: 3245834
    duration: 356
  - title: 06. 多了一隻豬腳
    size: 3631047
    duration: 399
  - title: 07. 機智的伊索
    size: 4086923
    duration: 454
  - title: 08. 三次開口
    size: 4918502
    duration: 520
  - title: 09. 替主人解危
    size: 4875556
    duration: 515
  - title: 10. 出爾反爾
    size: 3736045
    duration: 394
  - title: 11. 解開預兆
    size: 4677850
    duration: 502
  - title: 12. 伊索和他的故事
    size: 4916745
    duration: 525
  - title: 13. 以德報怨
    size: 3814932
    duration: 421
  - title: 14. 埃及王服輸
    size: 4350649
    duration: 468
  - title: 15. 被害入獄
    size: 4700141
    duration: 508
  - title: 16. 永遠流傳的寓言
    size: 5414964
    duration: 582
